add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$line_break\
$character"""

[directory]
truncation_length = 0
truncate_to_repo = true
style = "blue bold"

[git_branch]
symbol = ""
style = "bold"
format = "on [$branch]($style) "

[git_status]
style = "red"
format = "[$all_status$ahead_behind]($style) "

[character]
success_symbol = "[❯](white)"
error_symbol = "[❯](red)"
