# Minimal prompt - directory and character only
SPACESHIP_PROMPT_ORDER=(
  dir
  git
  line_sep
  char
)

# Directory
SPACESHIP_DIR_TRUNC=0              # Don't truncate
SPACESHIP_DIR_TRUNC_REPO=true      # Show only repo name when in git repo

# Git
SPACESHIP_GIT_SHOW=true
SPACESHIP_GIT_BRANCH_SHOW=true
SPACESHIP_GIT_BRANCH_PREFIX=""       # Remove branch icon
SPACESHIP_GIT_STATUS_SHOW=true

# Character
SPACESHIP_CHAR_SYMBOL="❯ "
SPACESHIP_CHAR_SYMBOL_SUCCESS="❯ "
SPACESHIP_CHAR_SYMBOL_FAILURE="❯ "
SPACESHIP_CHAR_COLOR_SUCCESS="white"
SPACESHIP_CHAR_COLOR_FAILURE="red"

# Disable everything else
SPACESHIP_NODE_SHOW=false
SPACESHIP_GCLOUD_SHOW=false
SPACESHIP_PACKAGE_SHOW=false
SPACESHIP_PYTHON_SHOW=false
SPACESHIP_RUBY_SHOW=false
SPACESHIP_GOLANG_SHOW=false
SPACESHIP_RUST_SHOW=false
SPACESHIP_DOCKER_SHOW=false
SPACESHIP_AWS_SHOW=false
SPACESHIP_KUBECTL_SHOW=false
SPACESHIP_TERRAFORM_SHOW=false
SPACESHIP_TIME_SHOW=false
SPACESHIP_BATTERY_SHOW=false
SPACESHIP_EXEC_TIME_SHOW=false
